### ISSUE TITLE
Great looking code.  One minor adjustment

### ISSUE THREAD

**Issue by mpmenne** [nickmoel/mario#3]
Hey Nick. awesome code man.  I really like how you are using interfaces and patterns.  Keep up the good work.

One minor point for consideration.  Always strive to make your object immutable.  For example on the PyramidFactory, pass the rows in through the constructor instead of the setter (and remove the setter).  By using only the constructor you create a brand new fresh pyramid everytime (with none of the left over stuff from before).

**Comment by nickmoel** [comment]
made the changes, thanks!
